-- MySQL Script generated by MySQL Workbench
-- Tue Oct 29 03:56:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbSisma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbSisma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbSisma` ;
USE `dbSisma` ;

-- -----------------------------------------------------
-- Table `dbSisma`.`TipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`TipoUsuario` (
  `idTipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Persona_TipoPersona1_idx` (`idTipoUsuario` ASC),
  CONSTRAINT `fk_Persona_TipoPersona1`
    FOREIGN KEY (`idTipoUsuario`)
    REFERENCES `dbSisma`.`TipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`Grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`Grado` (
  `idGrado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`idGrado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `nombre` NVARCHAR(50) NOT NULL,
  `anho` INT NOT NULL,
  `idProfesor` INT NOT NULL,
  `idGrado` INT NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `fk_Curso_Persona_idx` (`idProfesor` ASC),
  INDEX `fk_Curso_Grado1_idx` (`idGrado` ASC),
  CONSTRAINT `fk_Curso_Persona`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `dbSisma`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_Grado1`
    FOREIGN KEY (`idGrado`)
    REFERENCES `dbSisma`.`Grado` (`idGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`Periodo` (
  `idPeriodo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPeriodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`Evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`Evaluacion` (
  `idEvaluacion` INT NOT NULL AUTO_INCREMENT,
  `fechaEntrega` DATETIME NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `valor` INT NOT NULL,
  `idPeriodo` INT NOT NULL,
  PRIMARY KEY (`idEvaluacion`),
  INDEX `fk_Evaluacion_Periodo1_idx` (`idPeriodo` ASC),
  CONSTRAINT `fk_Evaluacion_Periodo1`
    FOREIGN KEY (`idPeriodo`)
    REFERENCES `dbSisma`.`Periodo` (`idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`EvaluacionXUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`EvaluacionXUsuario` (
  `idEvaluacionXUsuario` INT NOT NULL AUTO_INCREMENT,
  `idEvaluacion` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`idEvaluacionXUsuario`),
  INDEX `fk_Evaluacion_has_Persona_Persona1_idx` (`idUsuario` ASC),
  INDEX `fk_Evaluacion_has_Persona_Evaluacion1_idx` (`idEvaluacion` ASC),
  CONSTRAINT `fk_Evaluacion_has_Persona_Evaluacion1`
    FOREIGN KEY (`idEvaluacion`)
    REFERENCES `dbSisma`.`Evaluacion` (`idEvaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluacion_has_Persona_Persona1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `dbSisma`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`UsuarioXCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`UsuarioXCurso` (
  `idUsuarioXCurso` INT NOT NULL AUTO_INCREMENT,
  `idEstudiante` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`idUsuarioXCurso`),
  INDEX `fk_Persona_has_Curso_Curso1_idx` (`idCurso` ASC),
  INDEX `fk_Persona_has_Curso_Persona1_idx` (`idEstudiante` ASC),
  CONSTRAINT `fk_Persona_has_Curso_Persona1`
    FOREIGN KEY (`idEstudiante`)
    REFERENCES `dbSisma`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Curso_Curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `dbSisma`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`EvaluacionXCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`EvaluacionXCurso` (
  `idEvaluacionXCurso` INT NOT NULL AUTO_INCREMENT,
  `idEvaluacion` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idEvaluacionXCurso`),
  INDEX `fk_Evaluacion_has_Curso_Curso1_idx` (`idCurso` ASC),
  INDEX `fk_Evaluacion_has_Curso_Evaluacion1_idx` (`idEvaluacion` ASC),
  CONSTRAINT `fk_Evaluacion_has_Curso_Evaluacion1`
    FOREIGN KEY (`idEvaluacion`)
    REFERENCES `dbSisma`.`Evaluacion` (`idEvaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluacion_has_Curso_Curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `dbSisma`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
