-- MySQL Script generated by MySQL Workbench
-- Wed Oct 23 17:38:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbSisma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbSisma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbSisma` ;
USE `dbSisma` ;

-- -----------------------------------------------------
-- Table `dbSisma`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`Persona` (
  `idPersona` INT NOT NULL,
  `nobmre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `email` NVARCHAR(200) NOT NULL,
  `contrasena` VARBINARY(50) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`Grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`Grado` (
  `idGrado` INT NOT NULL,
  `nombre` NVARCHAR(50) NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`idGrado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`Curso` (
  `idCurso` INT NOT NULL,
  `nombre` NVARCHAR(50) NOT NULL,
  `anho` DATE NOT NULL,
  `idProfesor` INT NOT NULL,
  `idGrado` INT NOT NULL,
  PRIMARY KEY (`idCurso`, `idProfesor`, `idGrado`),
  INDEX `fk_Curso_Persona_idx` (`idProfesor` ASC),
  INDEX `fk_Curso_Grado1_idx` (`idGrado` ASC),
  CONSTRAINT `fk_Curso_Persona`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `dbSisma`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_Grado1`
    FOREIGN KEY (`idGrado`)
    REFERENCES `dbSisma`.`Grado` (`idGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`Periodo` (
  `idPeriodo` INT NOT NULL,
  `nombre` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPeriodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`Evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`Evaluacion` (
  `idEvaluacion` INT NOT NULL,
  `fechaEntrega` DATETIME NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `valor` INT NOT NULL,
  `idPeriodo` INT NOT NULL,
  PRIMARY KEY (`idEvaluacion`, `idPeriodo`),
  INDEX `fk_Evaluacion_Periodo1_idx` (`idPeriodo` ASC),
  CONSTRAINT `fk_Evaluacion_Periodo1`
    FOREIGN KEY (`idPeriodo`)
    REFERENCES `dbSisma`.`Periodo` (`idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`EvaluacionXPersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`EvaluacionXPersona` (
  `idEvaluacionXPersona` VARCHAR(45) NOT NULL,
  `idEvaluacion` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`idEvaluacion`, `idPersona`, `idEvaluacionXPersona`),
  INDEX `fk_Evaluacion_has_Persona_Persona1_idx` (`idPersona` ASC),
  INDEX `fk_Evaluacion_has_Persona_Evaluacion1_idx` (`idEvaluacion` ASC),
  CONSTRAINT `fk_Evaluacion_has_Persona_Evaluacion1`
    FOREIGN KEY (`idEvaluacion`)
    REFERENCES `dbSisma`.`Evaluacion` (`idEvaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluacion_has_Persona_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `dbSisma`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`PersonaXCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`PersonaXCurso` (
  `idPersonaXCurso` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`idPersonaXCurso`, `idPersona`, `idCurso`),
  INDEX `fk_Persona_has_Curso_Curso1_idx` (`idCurso` ASC),
  INDEX `fk_Persona_has_Curso_Persona1_idx` (`idPersona` ASC),
  CONSTRAINT `fk_Persona_has_Curso_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `dbSisma`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Curso_Curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `dbSisma`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbSisma`.`EvaluacionXCurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbSisma`.`EvaluacionXCurso` (
  `idEvaluacionXCurso` INT NOT NULL,
  `idEvaluacion` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idEvaluacionXCurso`, `idEvaluacion`, `idCurso`),
  INDEX `fk_Evaluacion_has_Curso_Curso1_idx` (`idCurso` ASC),
  INDEX `fk_Evaluacion_has_Curso_Evaluacion1_idx` (`idEvaluacion` ASC),
  CONSTRAINT `fk_Evaluacion_has_Curso_Evaluacion1`
    FOREIGN KEY (`idEvaluacion`)
    REFERENCES `dbSisma`.`Evaluacion` (`idEvaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluacion_has_Curso_Curso1`
    FOREIGN KEY (`idCurso`)
    REFERENCES `dbSisma`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
